apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prom-admin
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prom-rbac
#https://kubernetes.io/docs/reference/access-authn-authz/rbac/
#For all service accounts in the “qa” namespace
subjects:
  - kind: Group
    name: system:serviceaccounts:prometheus
    namespace: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: prom-admin
  apiGroup: rbac.authorization.k8s.io
