apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: no-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dave-access
subjects:
  - kind: ServiceAccount
    name: dave
    namespace: default
roleRef:
  kind: Role
  name: no-access
  apiGroup: rbac.authorization.k8s.io
