apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: negleb/nginx-static-site:v1.1.1
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
        - name: exporter
          image: nginx/nginx-prometheus-exporter:0.8.0
          ports:
            - name: metrics
              containerPort: 9113
              protocol: TCP
          args: ["-nginx.scrape-uri", "http://127.0.0.1:80/basic_status"]
