apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-mon
spec:
  selector:
    matchLabels:
      app: nginx-web
  endpoints:
    - port: metrics
      path: "/metrics"
      interval: 15s
