prometheusOperator:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

grafana:
  adminPassword: 1q2w3e4r
  ingress:
    enabled: true
    hosts:
      - grafana.130.211.59.197.xip.io

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.130.211.59.197.xip.io

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule

alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
