apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: shop.35.228.239.193.nip.io
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
  tls:
  - hosts:
    - shop.35.228.239.193.nip.io
    secretName: frontend-ingress-cert
