apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: app
spec:
  containers:
    - name: web
      image: negleb/otus-k8s-hw-2_web-app:2.0.0
      volumeMounts:
        - name: app
          mountPath: /app
      env:
        - name: SERVER_FOLDER
          value: "/app"
  initContainers:
    - name: init-index-page
      image: busybox:1.31.0
      command:
        [
          "sh",
          "-c",
          "wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh",
        ]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
